



      
        
        
        
          
        
      
      
      
      
      
      
      
        
      
      
        
        
      
    
      
    
      
      
      





    




    
    












    









    



    




    




















    
  










 













  
  

















    




    



    



    



    
























    












    

     

    
        
    
    

    
    

    
    
        
    
    
    
        
    













    
























    







    










































                                                                                                                                                                                                                                                          <!DOCTYPE HTML><html><head><meta charset="utf-8"><meta name="aplus-waiting" content="MAN"><meta name="keywords" content=""><meta name="description" content="">   <meta name="wh-pid" content="dailyAct-257518">   <meta charset="utf-8"/>
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
<link rel="dns-prefetch" href="//g.alicdn.com"/>
<link rel="dns-prefetch" href="//img.alicdn.com"/>
<link rel="dns-prefetch" href="//bar.tmall.com"/>
<link href="//www.taobao.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link title="天猫Tmall.com" href="//g.alicdn.com/mui/global/1.2.35/file/search.xml" type="application/opensearchdescription+xml" rel="search"/>

<meta name="spm-id" content="a211oj.24780012"/>



<title>淘宝女装PC频道新品2021.9-淘！我喜欢</title>

<script>
    window.g_config = window.g_config || {
        devId: 'pc',
        headerVersion: '1.4.0',
        loadModulesLater: true,
        language: '',
        
        
        sl: 'node'
    };
</script>


<base target="_blank"/>
 
    
        
    













    






    
        <link rel="stylesheet" href="//g.alicdn.com/mui/common/5.0.17/index-pc.css" />
<script>window.g_config = window.g_config || {};window.g_config.loadedCss = window.g_config.loadedCss || [];window.g_config.loadedCss = ["@ali/mui-common/index-pc.css"];</script>
    









<script src="//g.alicdn.com/secdev/pointman/js/index.js" app="tmall"></script>
  
      <meta name="wpk-bid" content="jstracker">
      <script src="//g.alicdn.com/??tb/tracker/5.0.3/index.js,jstracker/jstracker-tes/0.0.3/index.js" crossOrigin="anonymous"></script>
      <script>  var __isLocalDev = false; var __systemPreviewEnv = ''; var __useDataService = true; var __usePrefetch = true; var __useAsyncRender = false; var __useH5AsyncRender = true; var __useFsDataCache = false; var __useClientSsr = false; var __pageCreatePlatform = 'ark-act'; var __detectedDevice = 'pc'; var __inApp = false; var __isZcache = false; var __isAliIntranet = false; var __pageSolution = 'pegasus'; var __lazyloadScript = true; var __shareConfig = {"shareTitle":"天猫tmall.com-理想生活上天猫","shareInfo":"天猫tmall.com-理想生活上天猫","shareImgUrl":"//img.alicdn.com/tps/i3/TB18.tYMXXXXXXvXFXXh7Qm2pXX-750-750.png","shareBizId":"2688"}; var __customConfig = {"lzyScript":true,"consolebridge":true,"inlineCss":true,"lzysf":true,"nomtsdk":true,"customBarName":"mmod-zebra-magical-1143-1556442367562","customBarFullName":"@ali/mmod-zebra-magical-1143-1556442367562","headerFooterComponent":"@ali/pmod-zebra-tb-headerfooter/5.0.2","headAssets":true,"hideDefaultTitle":true,"titleExtra":"淘！我喜欢","favIcon":"//www.taobao.com/favicon.ico","navbarVersion":"5.0.51","firstScreenDynamicAmount":2,"firstScreenModAmount":10,"includeWeexDeclare":"false","includeHtmlDocType":"false","useJSTracker":true,"shareConfig":{"shareTitle":"天猫tmall.com-理想生活上天猫","shareInfo":"天猫tmall.com-理想生活上天猫","shareImgUrl":"//img.alicdn.com/tps/i3/TB18.tYMXXXXXXvXFXXh7Qm2pXX-750-750.png","shareBizId":"2688"}};  var __fedataConfig = {"enableKangarooBlockExtranet":false};   var __renderType = 'rax'; var __autoDisablePushWindow = false;     var __useConsoleBridge = true;   var __lazyloadSufei = true;       var __rax_adapter = {"type":"px","ratio":990};  var __useEs6 = false;   var __pageTheme = {"floorTitleIcon":"https://gw.alicdn.com/tfs/TB1X6f7dTtYBeNjy1XdXXXXyVXa-120-48.png","enableBaseColor":true,"backgroundColor":"#d6ca8f"};    var __kangarooBottomConfig = {

};   window.g_config = window.g_config || {};  window.g_config.language = "";  window.g_config.regionID = "CN";    window.__serverTimeStr = "2021-12-14T15:40:00+08:00";    </script>  <link rel="stylesheet" type="text/css" href="https://g.alicdn.com/??code/npm/@ali/css-grid/0.0.2/grid.css,pmod/act-style/5.0.1/act.css">                      <link rel="stylesheet" href="https://g.alicdn.com/tbhome/tb-nav/index.css">   </head><body><script>
with(document)with(body)with(insertBefore(createElement("script"),firstChild))setAttribute("exparams","category=&userid=&aplus&yunid=&&asid=AQAAAACbS7hhGPeqBAAAAAAi45iyDUO3jQ==",id="tb-beacon-aplus",src=(location>"https"?"//g":"//g")+".alicdn.com/alilog/mlog/aplus_v2.js")
</script>
                       <section id="content"><style>#mallPage{background-color: #d6ca8f; }   #recyclerview {
                        overflow: auto !important;
                    }  </style> <div class="mui-zebra-page" data-page-id="1287144" data-page-schema-version="297b272a-778d-4824-aa78-5347d84c407f">    </div> </section>                  <script src="https://g.alicdn.com/tbhome/tb-nav/index.js"></script>      <script src="//g.alicdn.com/??mui/feloader/5.0.14/feloader-min.js,mui/kissy/5.0.2/seed-min.js,rax-pkg/rax/1.2.0/index.js,code/npm/@ali/pcom-appear/0.0.8/index.js,pmod/base/5.2.42/utils.js,mui/bat/5.0.11/index.js,mui/jstracker-bat/5.0.9/index-native.js,pmod/fedata/5.1.65/index-bundle.js,pmod/base/5.2.42/log.js,rax-pkg/universal-env/3.2.2/index.js,rax-pkg/rax-view/1.0.1/index.js,rax-pkg/rax-text/1.2.1/index.js,rax-pkg/rax-image/1.1.0/index.js,code/npm/@ali/pcom-page-error/4.0.4/index.js,rax-pkg/rax-link/1.4.3/index.js,code/npm/@ali/pcom-tracker-link/0.3.15/index.js,rax-pkg/rax-picture/1.1.7/index.js,code/npm/@ali/pcom-floor-title/0.0.18/index.js,mui/weex-zebra-utils/6.0.2/index-native.js,rax-pkg/rax-find-dom-node/1.0.0/index.js,rax-pkg/rax-refreshcontrol/1.0.0/index.js,rax-pkg/rax-scrollview/1.1.4/index.js,rax-pkg/rax-children/1.0.0/index.js,rax-pkg/rax-proptypes/1.0.0/index.js,rax-pkg/rax-recyclerview/1.1.2/index.js,code/npm/@ali/pcom-pull-to-refresh/0.0.3/index.js,code/npm/@ali/pcom-alienv/1.0.1/index.js,code/npm/@ali/pcom-devicelevel/1.0.8/index.js,code/npm/@ali/pcom-driver/0.0.16/index.js,code/npm/@ali/pcom-behavior-assist/0.0.6/index.js,pmod/core-render/5.2.160/index-rax.js,mui/common/5.0.17/js/mod-config.js,mui/babel-polyfill/7.2.7/index.js,mui/common/5.0.17/js/event.js,mui/custom-event/5.0.0/index.js,mui/common/5.0.17/js/tm.js,mui/common/5.0.17/js/tool.js,mui/common/5.0.17/js/site-nav.js,mui/common/5.0.17/js/plugin-pc.js,mui/common/5.0.17/index-pc.js" crossOrigin="anonymous"></script>
<script src="//g.alicdn.com/??pmod/fedata/5.1.65/build-data-service-polyfill.js,code/npm/@ali/pcom-mtop/4.0.7/index.js,code/npm/@ali/pcom-fetch/2.0.9/index.js,code/npm/@ali/pcom-dynamic/1.0.30/index.js,code/npm/@ali/pcom-cookie/1.0.1/index.js" crossOrigin="anonymous"></script>                                                                                                              <script> !function(){var e;try{var i=document.querySelector('meta[name="wh-pid"]');e=i.getAttribute("content")}catch(r){}if(e){var a=window.location.href;window.require("@ali/pmod-base/utils",function(i){var r=(new i.Url).parse(a),n=r.params;if(n.wh_pid&&n.wh_pid!==e){delete r.params.wh_pid,r.params.wh_dataservice="false";var l=r.toString();l=l.replace(/upr|wupr/,n.wh_pid),window.location.replace(l)}})}}(); </script>  <script> var _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol?"symbol":typeof e},_classCallCheck=function(e,i){if(!(e instanceof i))throw new TypeError("Cannot call a class as a function")},_createClass=function(){function e(e,i){for(var a=0;a<i.length;a++){var r=i[a];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(i,a,r){return a&&e(i.prototype,a),r&&e(i,r),i}}(),_defineProperty=function(e,i,a){return i in e?Object.defineProperty(e,i,{"value":a,"enumerable":!0,"configurable":!0,"writable":!0}):e[i]=a,e},_extends=Object.assign||function(e){for(var i=1;i<arguments.length;i++){var a=arguments[i];for(var r in a)Object.prototype.hasOwnProperty.call(a,r)&&(e[r]=a[r])}return e},_inherits=function(e,i){if("function"!=typeof i&&null!==i)throw new TypeError("Super expression must either be null or a function, not "+typeof i);e.prototype=Object.create(i&&i.prototype,{"constructor":{"value":e,"enumerable":!1,"writable":!0,"configurable":!0}}),i&&(Object.setPrototypeOf?Object.setPrototypeOf(e,i):e.__proto__=i)},_interopRequireDefault=function(e){return e&&e.__esModule?e:{"default":e}},_interopRequireWildcard=function(e){if(e&&e.__esModule)return e;var i={};if(null!=e)for(var a in e)Object.prototype.hasOwnProperty.call(e,a)&&(i[a]=e[a]);return i["default"]=e,i},_possibleConstructorReturn=function(e,i){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!i||"object"!=typeof i&&"function"!=typeof i?e:i},_slicedToArray=function(){function e(e,i){var a=[],r=!0,n=!1,l=void 0;try{for(var o,m=e[Symbol.iterator]();!(r=(o=m.next()).done)&&(a.push(o.value),!i||a.length!==i);r=!0);}catch(u){n=!0,l=u}finally{try{!r&&m["return"]&&m["return"]()}finally{if(n)throw l}}return a}return function(i,a){if(Array.isArray(i))return i;if(Symbol.iterator in Object(i))return e(i,a);throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();  window.require(['@ali/pmod-core-render/index-rax'], function(WebBased) {
                new WebBased().start();
            });  </script>   </body></html> 







    


    
    


















    
    
    
    
    
        
            
            
            
            
                
            
            
            
        
    
        
            
            
            
            
                
            
            
            
        
    
        
            
            
            
            
                
            
            
            
        
    


    